src/Entity/Property.php
<?php

namespace App\Entity;

use App\Repository\PropertyRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;


#[ORM\Entity(repositoryClass: PropertyRepository::class)]
#[UniqueEntity("title")]
#[Vich\Uploadable]

class Property
{
    const heat = [
        0 => 'Electrique',
        1 => 'Gaz'
    ];

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;


    #[ORM\Column(length: 255, nullable: true)]
    private ?string $filename = null;

    #[Vich\UploadableField(mapping: 'property_image', fileNameProperty: 'filename')]
    private ?File $imageFile = null;

    #[ORM\Column(length: 255)]
    #[Assert\Length(min: 5, max: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column]
    #[Assert\Range(min: 10, max: 400)]
    private ?int $surface = null;

    #[ORM\Column]
    private ?int $rooms = null;

    #[ORM\Column]
    private ?int $bedrooms = null;

    #[ORM\Column]
    private ?int $floor = null;

    #[ORM\Column]
    private ?int $price = null;

    #[ORM\Column]
    private ?int $heat = null;

    #[ORM\Column(length: 255)]
    private ?string $city = null;

    #[ORM\Column(length: 255)]
    private ?string $address = null;

    #[ORM\Column(length: 255)]
    #[Assert\Regex("/^[0-9]{5}$/")]
    private ?string $postal_code = null;

    #[ORM\Column(options: ['default' => false])]
    private ?bool $sold = false;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\ManyToMany(targetEntity: Option::class, inversedBy: 'properties')]
    private Collection $options;

    #[ORM\Column]
    private ?\DateTimeImmutable $updated_at;

    public function __construct()
    {
        $this->created_at = new \DateTimeImmutable();
        $this->options = new ArrayCollection();
        $this->updated_at = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->title);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): static
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): static
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): static
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): static
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getFormattedPrice(): string
    {
        return number_format($this->price, 0, '', ' ');
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): static
    {
        $this->heat = $heat;

        return $this;
    }

    public function getHeatType(): string
    {
        return self::heat[$this->heat];
    }

    public function getCity(): ?string
    {
        return $this->city;
    }


    public function setCity(string $city): static
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): static
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): static
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function isSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): static
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection<int, Option>
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): static
    {
        if (!$this->options->contains($option)) {
            $this->options->add($option);
            $option->addProperty($this);
        }

        return $this;
    }

    public function removeOption(Option $option): static
    {
        if ($this->options->removeElement($option)) {
            $option->removeProperty($this);
        }

        return $this;
    }

    public function getFilename(): ?string
    {
        return $this->filename;
    }

    public function setFilename(?string $filename): void
    {
        $this->filename = $filename;
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;
        if ($this->imageFile instanceof UploadedFile) {
            $this->updated_at = new \DateTimeImmutable('now');
        }
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Option;
use App\Entity\Property;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('surface')
            ->add('rooms')
            ->add('bedrooms')
            ->add('floor')
            ->add('price')
            ->add('heat', ChoiceType::class, [
                'choices' => $this->getChoices()
            ])
            ->add('options', EntityType::class, [
                'class' => Option::class,
                'choice_label' => 'name',
                'required' => false,
                'multiple' => true
            ])
            ->add('imageFile', FileType::class, ['required' => false])
            ->add('city')
            ->add('address')
            ->add('postal_code')
            ->add('sold');
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
            'translation_domain' => 'forms'
        ]);
    }

    private function getChoices()
    {
        $choices = Property::heat;
        $output = [];
        foreach ($choices as $k => $v) {
            $output[$v] = $k;
        }
        return $output;
    }
}

src/Controller/PropertyController.php
<?php

namespace App\Controller;

use App\Entity\Contact;
use App\Entity\Property;
use App\Form\ContactType;
use App\Controller\ContactController;
use App\Repository\OptionRepository;
use App\Repository\PropertyRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PropertyController extends AbstractController
{

  private $repository;
  private $entity;

  public function __construct(PropertyRepository $repository, EntityManagerInterface $entity)
  {
    $this->repository = $repository;
    $this->entity = $entity;
  }


  #[Route('/biens', name: 'property_index')]
  public function index(OptionRepository $optionRepository, PaginatorInterface $paginator, Request $request): Response
  {
    $userPrice = "";
    $userRooms = "";
    $userOptions = [];

    if ($this->isCsrfTokenValid('search', $request->get('_token'))) {
      $userPrice = $request->get('userPrice');
      $userRooms = $request->get('userRooms');
      $userOptions = $request->get('userOptions');
      $query = $this->repository->findFilteredQuery($userPrice, $userRooms, $userOptions);
    } else {
      $query = $this->repository->findVisibleQuery()->getQuery();
    }

    $optionList = $optionRepository->findAll();
    $properties = $paginator->paginate(
      $query,
      $request->query->getInt('page', 1),
      12
    );

    return $this->render('property/index.html.twig', [
      'current_menu' => 'properties',
      'properties' => $properties,
      'user_price' => $userPrice,
      'user_rooms' => $userRooms,
      'user_options' => $userOptions,
      'option_list' => $optionList
    ]);
  }

  #[Route('/biens/{slug}-{id}', name: 'property_show', requirements: ['slug' => "^[a-z]+(?:-[a-z]+)*$"])]
  public function show(Property $property, string $slug, Request $request, ContactController $notification): Response
  {
    
    if ($property->getSlug() !== $slug) {
      return $this->redirectToRoute('property_show', [
        'id' => $property->getId(),
        'slug' => $property->getSlug()
      ], 301);
    }
    
    $contact = new Contact();
    $contact->setProperty($property);
    $form = $this->createForm(ContactType::class, $contact);
    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
      $notification->notify($contact);
      $this->addFlash('success', 'Votre email abien été envoyé');
      return $this->redirectToRoute('property_show', [
        'id' => $property->getId(),
        'slug' => $property->getSlug()
      ]);
    }

    return $this->render('property/show.html.twig', [
      'property' => $property,
      'current_menu' => 'properties',
      'form' => $form->createView()
    ]);
  }
}

templates/property/_property.html.twig
<div class="card mb-4" style="height: 30rem">
	{% if property.filename %}
	<img class="" src="{{ property.filename }}" alt="card-img-top">
	{% endif %}
	<div class="d-flex flex-column justify-content-center card-body">
		<h5 class="card-title">
			<a href="{{ path('property_show', {slug: property.slug, id: property.id}) }}">{{ property.title }}</a>
		</h5>
		<p class="card-text">{{ property.description }}</p>
		<p class="card-text">{{ property.city }}
			({{ property.postalCode }})</p>
		<div class="text-primary" style="font-size:2rem; font-weight:bold;">
			{{ property.formattedPrice }}
			€
		</div>
	</div>
</div>

templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title 'Tous nos biens' %}

{% block body %}
	<div class="container mt-4 text-center">
		<h1 class="mb-5">Tous nos biens</h1>
		<form class="form-search mb-4" action="{{ path('property_index') }}" method="POST">
			<div class="form-floating mb-3">
				<input id="userRooms" type="number" min="1" value="{{ user_rooms }}" name="userRooms" class="form-control" placeholder="Nb de pièces">
				<label for="userRooms">Nombre de pièce maximum</label>
			</div>
			<div class="form-floating mb-3">
				<input type="number" min="1" value="{{ user_price }}" name="userPrice" class="form-control" placeholder="Prix max">
				<label for="userPrice">Prix maximum</label>
			</div>
			<div class="input-group mb-3">
				<label class="mb-1" for="userOptions">Ajouter une option...</label>
				<select id="userOptions" name="userOptions" class="w-100 form-select" multiple>
					<option selected value="">Pas d'option</option>
					{% for option in option_list %}
					<option value="{{ option.id }}">{{ option.name }}</option>
					{% endfor %}
				</select>
			</div>
			<input type="hidden" name="_token" value="{{ csrf_token('search')}}">
			<button class="btn btn-primary">Rechercher</button>
		</form>
		{% if properties|length %}
			<div class="row">
				{% for property in properties %}
					<div class="col-md-4">
						{% include 'property/_property.html.twig' %}
					</div>
				{% endfor %}
			</div>
			<div class="d-flex justify-content-center pagination">
				{{ knp_pagination_render(properties) }}
			</div>
		{% else %}
			<div class="alert alert-warning">Aucun résultat ne corresponds à votre recherche.</div>
		{% endif %}
	</div>
{% endblock %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}

{% block title property.title %}

{% block body %}
	<div class="bg-light txt-center p-5">
		<div class="container">

			{% for message in app.flashes('success') %}
				<div class="alert alert-success">
					{{ message }}
				</div>
			{% endfor %}

			{% if not form.vars.valid %}
				<div class="alert alert-danger">
					Veuillez insérer des champs valides.
				</div>
			{% endif %}

			<div class="row">
				<div class="col-md-8">
					{% if property.filename %}
					<img class="w-100 h-auto" src="{{ property.filename }}" alt="card-img-top">
					{% endif %}
				</div>
				<div class="col-md-4">
					<h1>{{ property.title }}</h1>
					<h2>{{ property.rooms }}
						pièces -
						{{ property.surface }}
						m2</h2>
					<div class="text-primary" style="font-size: 4rem;font-weight:bold;">{{ property.formattedPrice }}
						€</div>
					<a href="#" class="btn btn-primary" id="contactButton" {% if form.vars.submitted %} style="display: none;" {% endif %} >Contacter l'agence</a>
					<div id="contactForm" class="mt-4" {% if not form.vars.submitted %} style="display: none;" {% endif %}>
						{{ form_start(form) }}
						<div class="row">
							<div class="col">{{ form_row(form.firstname) }}</div>
							<div class="col">{{ form_row(form.lastname) }}</div>
						</div>
						<div class="row">
							<div class="col">{{ form_row(form.phone) }}</div>
							<div class="col">{{ form_row(form.email) }}</div>
						</div>
						{{ form_rest(form) }}
						<div class="form-group">
							<button class="btn btn-primary">Envoyer</button>
						</div>
						{{ form_end(form) }}
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="container mt-4">
		<p>{{ property.description | nl2br }}</p>
		<div class="row">
			<div class="col-md-8">
				<h2>Caractéristiques</h2>
				<table class="table table-striped">
					<tr>
						<td>Surface habitable</td>
						<td>{{ property.surface }}
							m2</td>
					</tr>
					<tr>
						<td>Pièces</td>
						<td>{{property.rooms }}</td>
					</tr>
					<tr>
						<td>Chambres</td>
						<td>{{ property.bedrooms }}</td>
					</tr>
					<tr>
						<td>Etages</td>
						<td>{{property.floor }}</td>
					</tr>
					<tr>
						<td>Chauffage</td>
						<td>{{ property.heatType }}</td>
					</tr>
				</table>
			</div>
			<div class="col-md-4">
				<h2>Spécificités</h2>
				<ul class="list-group">
					{% for option in property.options %}
					<li class="list-group-item">{{ option.name }}</li>
					{% endfor %}
				</ul>
			</div>
		</div>
	</div>
{% endblock %}